spring.application.name=cita-service

spring.config.import=optional:configserver:http://localhost:8888

# Activa la configuración en la nube
spring.cloud.config.enabled=true

# Esto evitará que se quede pegado eternamente si hay error de red
spring.cloud.config.fail-fast=true